name: Security Audit
on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    paths:
      - Cargo.toml
jobs:
  security_audit:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Security Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}