name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - 1.60.0  # MSRV
          - stable
          - beta
          - nightly
        features:
          - ""
          - "zeroize"
          - "rand"
          - "block-cipher"
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --no-default-features --features "${{ matrix.features }}"
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features --features "${{ matrix.features }}"
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --no-default-features --features "${{ matrix.features }}"
